CREATE DATABASE server_page;

USE server_page;

CREATE TABLE videos(
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    url TEXT NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    iduser int(11),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users(
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE `user` ADD FOREIGN KEY (`id`) REFERENCES `videos` (`userid`);

DESCRIBE videos;